name: Build and Release

on:
  push:
    branches: [main]
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/release.yml"

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build and Release
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: "1.24.3"
          check-latest: true

      - name: Get current date and time
        id: datetime
        run: |
          echo "date=$(Get-Date -Format "yyyy.MM.dd")" >> $env:GITHUB_OUTPUT
          echo "time=$(Get-Date -Format "HHmm")" >> $env:GITHUB_OUTPUT
          echo "full=$(Get-Date -Format "yyyy.MM.dd-HHmm")" >> $env:GITHUB_OUTPUT
        shell: pwsh

      - name: Build
        run: |
          go build -ldflags "-s -w" -o SpotifySongTracker.exe

      - name: Check for existing release with same date
        id: check_release
        run: |
          $existingRelease = gh release list --limit 10 | Select-String -Pattern "v${{ steps.datetime.outputs.date }}"
          $useFullDatetime = if ($existingRelease) { "true" } else { "false" }
          echo "use_full_datetime=$useFullDatetime" >> $env:GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: pwsh

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631 # v2.2.2
        with:
          tag_name: ${{ steps.check_release.outputs.use_full_datetime == 'true' && format('v{0}', steps.datetime.outputs.full) || format('v{0}', steps.datetime.outputs.date) }}
          name: ${{ steps.check_release.outputs.use_full_datetime == 'true' && format('Release {0} ({1})', steps.datetime.outputs.date, steps.datetime.outputs.time) || format('Release {0}', steps.datetime.outputs.date) }}
          body: |
            Automated release from commit ${{ github.sha }}

            Changes:
            ${{ github.event.head_commit.message }}
          files: |
            SpotifySongTracker.exe
            README.md
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
